#!/usr/bin/env node
/**
 * Converts logo_anim_data JSON to firmware/src/logo_animations.h
 * Same frame/palette format as splash_animations.h, with generated grid size and 10-entry palette.
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const opt = (k, def) => {
  const i = args.indexOf(k);
  return i >= 0 ? args[i + 1] : def;
};

const IN_DIR = path.resolve(opt('--in', path.join(__dirname, 'logo_anim_data')));
const OUT_FILE = path.resolve(
  opt('--out', path.join(__dirname, '..', 'firmware', 'src', 'logo_animations.h'))
);

const PALETTE_SIZE = 10;

function safeIdent(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}

function hexToRgb565(hex) {
  if (!hex || hex === 'transparent') return 0x0000;
  let h = hex.replace('#', '');
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  const r = parseInt(h.substr(0, 2), 16);
  const g = parseInt(h.substr(2, 2), 16);
  const b = parseInt(h.substr(4, 2), 16);
  return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
}

function paletteToRgb565(palette) {
  const out = new Array(PALETTE_SIZE).fill(0x0000);
  for (let i = 0; i < palette.length && i < PALETTE_SIZE; i++) {
    out[i] = hexToRgb565(palette[i]);
  }
  return out;
}

function main() {
  const files = fs.readdirSync(IN_DIR).filter((f) => f.endsWith('.json'));
  if (files.length === 0) {
    console.error(`No JSON in ${IN_DIR}. Run generate_logo_anim.js first.`);
    process.exit(1);
  }

  let out = '';
  out += '// Generated by tools/convert_logo_to_c.js — do not edit by hand.\n';
  out += '#pragma once\n#include <stdint.h>\n\n';
  out += '#define LOGO_PALETTE_SIZE 10\n\n';

  const gridSizes = new Set();
  for (const file of files) {
    const data = JSON.parse(fs.readFileSync(path.join(IN_DIR, file), 'utf8'));
    const first = data.frames?.[0]?.grid;
    if (!Array.isArray(first) || !Array.isArray(first[0])) {
      throw new Error(`${file}: missing frames[0].grid`);
    }
    gridSizes.add(first.length);
    if (first.some((row) => row.length !== first.length)) {
      throw new Error(`${file}: grid must be square`);
    }
  }
  if (gridSizes.size !== 1) {
    throw new Error(`Mixed logo grid sizes are not supported: ${[...gridSizes].join(', ')}`);
  }
  const gridSize = [...gridSizes][0];
  const gridCells = gridSize * gridSize;
  out += `#define LOGO_GRID_SIZE ${gridSize}\n`;
  out += `#define LOGO_GRID_CELLS ${gridCells}\n\n`;

  out += 'typedef struct {\n';
  out += '    const char *name;\n';
  out += '    const char *category;\n';
  out += '    uint16_t frame_count;\n';
  out += '    const uint16_t *palette;\n';
  out += '    const uint8_t (*frames)[LOGO_GRID_CELLS];\n';
  out += '    const uint16_t *holds;\n';
  out += '} logo_anim_def_t;\n\n';

  const entries = [];

  for (const file of files.sort()) {
    const data = JSON.parse(fs.readFileSync(path.join(IN_DIR, file), 'utf8'));
    const ident = safeIdent(file.replace(/\.json$/, ''));
    const pal565 = paletteToRgb565(data.palette);
    out += `static const uint16_t logo_${ident}_palette[${PALETTE_SIZE}] = {`;
    out += pal565.map((c) => `0x${c.toString(16).toUpperCase().padStart(4, '0')}`).join(',');
    out += '};\n';

    out += `static const uint8_t logo_${ident}_frames[${data.frames.length}][LOGO_GRID_CELLS] = {\n`;
    for (const f of data.frames) {
      const flat = [];
      for (let r = 0; r < gridSize; r++) for (let c = 0; c < gridSize; c++) flat.push(f.grid[r][c]);
      out += '    {' + flat.join(',') + '},\n';
    }
    out += '};\n';

    out += `static const uint16_t logo_${ident}_holds[${data.frames.length}] = {`;
    out += data.frames.map((f) => f.hold).join(',');
    out += '};\n\n';

    entries.push({
      ident,
      name: data.name,
      category: data.category,
      count: data.frames.length,
    });
  }

  out += `#define LOGO_ANIM_COUNT ${entries.length}\n`;
  out += 'static const logo_anim_def_t logo_anims[LOGO_ANIM_COUNT] = {\n';
  for (const e of entries) {
    out += `    {"${e.name}", "${e.category}", ${e.count}, logo_${e.ident}_palette, logo_${e.ident}_frames, logo_${e.ident}_holds},\n`;
  }
  out += '};\n';

  fs.writeFileSync(OUT_FILE, out);
  console.log(`Wrote ${OUT_FILE} (${entries.length} animations, ${(out.length / 1024).toFixed(1)} KB)`);
}

main();
